### PR TITLE
Merge `amq-sort-imports` back into `sort-imports`

### PR DESCRIPTION
**Pull request by amatiasq**
The sorting style was too complex to my team needs, we only needed sorting by module name (and maybe separating import sentences without imported names).

Since there was no way to configure the extension I forked it, added a style configurator and published it as `amq-sort-imports` so we could start using it immediately.

But I think this feature might help other people so it would be nice if we could merge it back into `sort-imports` and publish it as version 2.4.0.

I've also replaced `registration.ts` with `on-save.ts` which I does a clearer encapsulation of the on-save behaviour.

Also there's a new config option which allow the user to configure how many blank lines should be inserted after the imports section.

### CODE REVIEW

**Comment by peterjuras** [comment]
Thanks a lot for your pull request! Could you move out your added style into a separate module like the other styles? Then the extension could be kept clean and the [atom-import-sort](https://github.com/renke/atom-import-sort) plugin could benefit from it as well!

**Comment by amatiasq** [comment]
But how will it be configured then if I move the new style to another repo? If you want to use the new style you won't be able too then.

**Comment by peterjuras** [comment]
Hi,

sadly I have to tell you that I can't work on this project anymore and I'm on the search for a new maintainer for this extension. Until then, this pull request will likely stay unmerged.

**Comment by amatiasq** [comment]
Hi @peterjuras that's so sad, this is a great extension can I help you maintaining it?

**Comment by peterjuras** [comment]
Hi!

Yes I'm open if you want to continue this extension. It would be great if you could also inquire about Microsoft's process for moving extensions from one publisher to another.

**Comment by amatiasq** [comment]
@peterjuras I couldn't find any information about migrating a extension between publishers. Are you sure it is an option?

**Comment by ferdaber** [comment]
It looks like the best way right now is to either add accounts under the same publisher in VSTS or to just unpublish and republish.

See Microsoft/vscode#3670.

**Comment by amatiasq** [comment]
@peterjuras As @ferdaber suggested I published [a new extension with the same name](https://marketplace.visualstudio.com/items?itemName=amatiasq.sort-imports). I guess this one can be left published with a deprecated message just as I did with my [`amq-sort-imports` version](https://marketplace.visualstudio.com/items?itemName=amatiasq.amq-sort-imports#overview).

I'm using the fork I created for this PR so I merged the last changes you had in this repository.

This is the markdown I used for the deprecated extension readme:

```markdown
# Deprecated

This version is not maintained anymore, please use [sort-imports](https://marketplace.visualstudio.com/items?itemName=amatiasq.sort-imports) instead.
```

**Comment by ferdaber** [comment]
VSTS support did get back to me and said that the best way to move ownership while preserving downloads and views and other stats is to add the next contributor/maintainer under the publisher name. Afterwards VSTS support are willing to change a publisher name for the owner of that name.

**Comment by amatiasq** [comment]
Sure, sounds like a better solution. @peterjuras if you have time you can add me as maintainer, my publisher id is `amatiasq`.

@ferdaber I just saw your issue offering yourself to maintain the project, I want the features I implemented merged so we both can share that responsibility, does that fit with your needs?

**Comment by peterjuras** [comment]
I'll be happy to add you as a maintainer, could you look up the steps that are required to do this? I couldn't find anything in the extensions/vscode documentation.

**Comment by ferdaber** [comment]
@amatiasq that works with me!
@peterjuras the combination of these steps should work
- https://docs.microsoft.com/en-us/vsts/extend/publish/overview#share
- https://docs.microsoft.com/en-us/vsts/accounts/change-account-ownership-vs

**Comment by peterjuras** [comment]
Sorry for the late reply.

I checked and it appears that I cannot do the first step, share is not an option for extensions (maybe only for the full Visual Studio?)

For the second step, it would create a problem for my VSTS account since I use my personal Microsoft Account for this and I use it for a lot of other things. I should have created a separate MS Account just for these extensions to make them easier to manage.

Since both of these steps are not really possible for me, I'd suggest you to publish the extensions yourself under a new/your publisher account. Afterwards we can create a deprecation message in this extension that suggests moving over to your extension. Is this ok for you?

**Comment by ferdaber** [comment]
@amatiasq can you republish your extension?

**Comment by peterjuras** [comment]
@amatiasq Did you get around to republish the extension?

**Comment by amatiasq** [comment]
Sorry I was AFK last week. I re-published the extension a month ago as I explained on [this comment](https://github.com/peterjuras/vsc-sort-imports/pull/18#issuecomment-332481035) and @ferdaber I just need your email to add you as publisher. I don't have other extensions and I can just add you as admin.

Also are we using this repository or should we move to my fork which contains the published code? In any case we both should be collaborators for it.

**Comment by peterjuras** [comment]
Ah sorry I missed that!

I'll deprecate and republish my extension soon with a link to your new extension.

**Comment by peterjuras** [comment]
A new version with a deprecation notice has been published, thanks again for continuing this extension!

**Comment by peterjuras** [comment]
@amatiasq could you enable issues in the new repo?

**Comment by peterjuras** [comment]
See #27, please enable issues on your repository.

**Comment by amatiasq** [comment]
@peterjuras sorry for the delay, different timezone I guess. Enabled.

**Pull request closed without merging**
