### PR TITLE
support typescript files

### PR DESCRIPTION
**Pull request by shalomdotnet**

### CODE REVIEW

**Comment by peterjuras** [comment]
Great addition! Ill check this out soon and check whether it works on my end!

**Comment by peterjuras** [comment]
Thanks again for your pull request. I came across a few issues which need to be resolved before this can be merged into the extension.

The extension uses babel to parse the source and extract the import statements. As mentioned in #1 , babel can't parse TypeScript which means we can't sort files where TypeScript only syntax is used.

Example where sorting TypeScript works:
```ts
import B from 'B';
import A from 'A';

console.log(A, B);
```

This works, since the file also only contains valid JavaScript, without any TypeScript sugar. Once you start using TypeScript specific syntax however, the sorting will no longer work:

```ts
import A from './A';
import B from './B';
import AA from './AA';

class Are<D, E> { // TS-ONLY!
  private s: E; // TS-ONLY!
  private d: D; // TS-ONLY!

  getS() {
    return this.s;
  }
}

const a = new Are<{}, {}>(); // TS-ONLY!
console.log(a.getS());
```

To get sorting working with TypeScript files, the [import-sort](https://github.com/renke/import-sort) module needs to be adjusted to be able to handle TypeScript files.

**Comment by peterjuras** [comment]
Turns out the import-sort module was updated to sort TypeScript files. I updated to the newer version and sorting works now!

**Comment by shalomdotnet** [comment]
Thanks!

**Pull request merged**
